deanboard/deanboard/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('referrals.urls')),
    url(r'^referrals/', include('referrals.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^students/', include('students.urls')),
    url(r'^scholars/', include('students.urls')),
)

deanboard/referrals/urls.py
from django.conf.urls import patterns, url
from referrals import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

deanboard/students/urls.py
from django.conf.urls import patterns, url
from students import views

urlpatterns = patterns('',
    url(r'^/', views.index, name="index")
    )

deanboard/referrals/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from students.models import Scholar, Advisory

# Create your models here.

LEVEL_CHOICES = (
    (1, 'Teacher'),
    (2, 'Admin'),
    (3, 'Network Admin')
)

PREFIX_CHOICES = (
    (1, 'Mr.'),
    (2, 'Ms.'),
    (3, 'Mrs.'),
)

REASONS_CHOICES = (
    (1, 'Repeated Infractions'),
    (2, 'Walked Out'),
    (3, 'Walked Away/Ignored'),
    (4, 'Abusive/Profane Language'),
    (5, 'Threatening/Bullying'),
    (6, 'Harassment (sexual, racial, etc.)'),
    (7, 'Preventing continuation of class'),
    (8, 'Inappropriate response to a consequence'),
    (9, 'Horseplay'),
    (10, 'Fight'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    level = models.IntegerField(choices=LEVEL_CHOICES, default=1)
    prefix = models.IntegerField(choices=PREFIX_CHOICES)

    def __unicode__(self):
        return self.user.username


class Referral(models.Model):
    scholar = models.ForeignKey(Scholar)
    staff = models.ForeignKey(UserProfile)
    datetime = models.DateTimeField(auto_now=True)
    reason = models.IntegerField(choices=REASONS_CHOICES)
    description = models.CharField(max_length=1000, default="")

    def __unicode__(self):
        return self.id

deanboard/students/models.py
from django.db import models

# Create your models here.

GRADE_CHOICES = (
    (1, '5'),
    (2, '6'),
    (3, '7'),
    (4, '8'),
)


class Advisory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    grade = models.IntegerField(choices=GRADE_CHOICES)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "advisories"


class Scholar(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    kbid = models.IntegerField(unique=True, primary_key=True)
    advisory = models.ForeignKey(Advisory)

deanboard/referrals/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import RequestContext
from referrals.models import Referral


def index(request):
    context = RequestContext(request)
    referrals_list = Referral.objects.order_by('-datetime')[:5]
    context_dict = {'referrals': referrals_list}

    return render_to_response('referrals/index.html', context_dict, context)

deanboard/students/views.py
from django.shortcuts import render, render_to_response

# Create your views here.


def index(request):
    return HttpResponese('Hello, World!')

deanboard/templates/referrals/index.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Referrals</title>

        <!-- Bootstrap CSS -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    <br/>
    <br/>
    <div class="container">
        {% if referrals %}
        <ul>
            {% for referral in referrals %}
            <div class="well">
                <li><h2>{{ referral.scholar.first_name }} {{referral.scholar.last_name}}</h2></li>
                <li><strong>Advisory :</strong> {{referral.scholar.advisory}}</li>
                <li><strong>Referrer: </strong>{{referral.staff.get_prefix_display}} {{referral.staff.user.last_name}}, {{referral.staff.get_level_display}}</li>
                <li><strong>Date: </strong>{{referral.datetime}}</li>
                <li><strong>Reason: </strong>{{referral.get_reason_display}}</li>
                <li><strong>Description: </strong>{{referral.description}}</li>
            </div>
            {% endfor %}
        {% else %}
        <div class="well">
            <strong>No referrals.</strong>
        </div>
        {% endif %}
    </div>



        <!-- jQuery -->
        <script src="//code.jquery.com/jquery.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    </body>
</html>